parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: '20122012'
    mailer_transport: "gmail"
    mailer_encryption: "ssl"
    mailer_auth_mode: "login"
    mailer_host: "smtp.gmail.com"
    mailer_user: "cronosmen@gmail.com"
    mailer_password: "cronosmen2012201"
    locale: es
    secret: '20122012'
    database_path: null
